# Generated by Django 5.0.8 on 2025-03-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='metrics',
            field=models.JSONField(default=dict),
        ),
    ]
