# Generated by Django 5.0.8 on 2025-03-01 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_trainedmodel_metrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainedmodel',
            name='metrics',
        ),
    ]
