# Generated by Django 5.0.8 on 2025-03-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_trainedmodel_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='accuracy',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='f1_score',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='loss',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='precision',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='recall',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='class_names',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='image_counts',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='model_paths',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='trained_models',
            field=models.JSONField(default=dict),
        ),
    ]
