# Generated by Django 5.0.8 on 2025-03-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_trainedmodel_accuracy_trainedmodel_f1_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('project_name', models.CharField(max_length=255)),
                ('epoch', models.IntegerField()),
                ('loss', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
