# Generated by Django 5.0.8 on 2025-03-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_trainingprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogress',
            name='model_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
