# Generated by Django 5.0.8 on 2025-03-31 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_trainingprogress_model_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingprogress',
            name='model_name',
        ),
    ]
