# Generated by Django 5.0.8 on 2025-04-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_trainingprogress_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogress',
            name='model_name',
            field=models.CharField(default='UnknownModel', max_length=255),
        ),
    ]
